name: Create Windows binary
on:
  push:
    branches:
      - master
      - main
jobs:
  build-image:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          cache: 'gradle'

      - name: Build Project
        run: |
          gradlew.bat build -Dquarkus.package.type=native -x test --no-daemon

      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: |
            build/*.exe
